[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[unix_http_server]
file=/tmp/supervisor.sock
chmod=0777

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock

[program:php-fpm]
command=php-fpm -F
directory=/var/www/html
user=www
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/log/supervisor/php-fpm.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=10



[program:http-server]
command=php -S 0.0.0.0:8080 -t /var/www/html/public -c /var/www/html/php.ini
directory=/var/www/html
user=www
autostart=false
autorestart=false
redirect_stderr=true
stdout_logfile=/var/log/supervisor/http-server.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=3

[program:laravel-schedule]
command=php artisan schedule:work
directory=/var/www/html
user=www
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/log/supervisor/laravel-schedule.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=10

[program:queue-worker]
command=php artisan queue:work redis --sleep=3 --tries=3 --max-time=3600
directory=/var/www/html
user=www
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/log/supervisor/queue-worker.log
stdout_logfile_maxbytes=50MB
