# Switch front + admin Vite env between local Docker and production API.
#
#   .\scripts\set-dev-mode.ps1 -Mode local-api      # API :8888 + yarn dev (default)
#   .\scripts\set-dev-mode.ps1 -Mode local-full     # full stack :9080
#   .\scripts\set-dev-mode.ps1 -Mode production     # UI local, API on goldtocash.us
#   .\scripts\set-dev-mode.ps1                      # show current mode
#
# After switching, restart yarn dev in front_admin / front if they are running.

param(
	[ValidateSet('local-api', 'local-full', 'production')]
	[string] $Mode
)

$ErrorActionPreference = 'Stop'
$RepoRoot = if ($PSScriptRoot) { (Resolve-Path (Join-Path $PSScriptRoot '..')).Path } else { (Get-Location).Path }
Set-Location -LiteralPath $RepoRoot

$ModeFile = Join-Path $RepoRoot '.dev-mode'
$ModesDir = Join-Path $RepoRoot 'config\dev-modes'

function Show-CurrentMode {
	if (-not (Test-Path -LiteralPath $ModeFile)) {
		Write-Host 'Current dev mode: (not set - default is local-api)' -ForegroundColor Yellow
		Write-Host '  Run:  .\scripts\set-dev-mode.ps1 -Mode local-api' -ForegroundColor DarkGray
		return
	}
	$current = (Get-Content -LiteralPath $ModeFile -Raw).Trim()
	Write-Host "Current dev mode: $current" -ForegroundColor Cyan
	$src = Join-Path $ModesDir "$current.env"
	if (Test-Path -LiteralPath $src) {
		Get-Content -LiteralPath $src | Where-Object { $_ -match '^\s*#' -or $_ -match '^\s*$' } | ForEach-Object {
			Write-Host "  $_" -ForegroundColor DarkGray
		}
	}
}

if (-not $Mode) {
	Show-CurrentMode
	Write-Host ''
	Write-Host 'Available modes:' -ForegroundColor Cyan
	Write-Host '  local-api     Docker API :8888, admin yarn :5173, login admin@local.debug / password'
	Write-Host '  local-full    Docker site :9080 + admin :9082 (or yarn with proxy :9080)'
	Write-Host '  production    yarn dev -> real m.goldtocash.us / goldtocash.us API'
	exit 0
}

$SourceEnv = Join-Path $ModesDir "$Mode.env"
if (-not (Test-Path -LiteralPath $SourceEnv)) {
	Write-Host "Missing mode file: $SourceEnv" -ForegroundColor Red
	exit 1
}

$lines = Get-Content -LiteralPath $SourceEnv
$viteLines = $lines | Where-Object {
	$_ -match '^\s*#' -or $_ -match '^\s*$' -or $_ -match '^\s*VITE_' -or $_ -match '^\s*(ADMIN_API_PROXY_TARGET|FRONT_API_PROXY_TARGET|DEV_MODE)='
}

$adminEnv = Join-Path $RepoRoot 'front_admin\.env.development.local'
$frontEnv = Join-Path $RepoRoot 'front\.env.development.local'

$header = @(
	'# Auto-generated by scripts/set-dev-mode.ps1 - do not edit by hand.',
	"# Re-apply:  .\scripts\set-dev-mode.ps1 -Mode $Mode",
	''
)

($header + $viteLines) | Set-Content -LiteralPath $adminEnv -Encoding utf8
($header + $viteLines) | Set-Content -LiteralPath $frontEnv -Encoding utf8
Set-Content -LiteralPath $ModeFile -Value $Mode -Encoding utf8 -NoNewline

Write-Host ''
Write-Host "Dev mode set to: $Mode" -ForegroundColor Green
Write-Host '  front_admin/.env.development.local' -ForegroundColor DarkGray
Write-Host '  front/.env.development.local' -ForegroundColor DarkGray
Write-Host ''

switch ($Mode) {
	'local-api' {
		Write-Host 'Start API:   .\scripts\start-debug-api.ps1' -ForegroundColor Cyan
		Write-Host 'Start admin: .\scripts\start-admin-dev.ps1' -ForegroundColor Cyan
		Write-Host 'Admin URL:   http://127.0.0.1:5173/login  (admin@local.debug / password)' -ForegroundColor Green
	}
	'local-full' {
		Write-Host 'Start stack: .\scripts\start-local-full.ps1' -ForegroundColor Cyan
		Write-Host 'Admin URL:   http://127.0.0.1:9082/login  (Docker) or yarn dev after mode switch' -ForegroundColor Green
		Write-Host 'Site URL:    http://127.0.0.1:9080/' -ForegroundColor Green
	}
	'production' {
		Write-Host 'No Docker required. Start admin:  cd front_admin, then yarn dev' -ForegroundColor Cyan
		Write-Host 'Uses production API - you need valid prod credentials.' -ForegroundColor Yellow
	}
}

Write-Host ''
Write-Host 'Restart Vite (yarn dev) if it was already running.' -ForegroundColor Yellow
